//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoodsStatistics
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DevConn : DbContext
    {
        public DevConn()
            : base("name=DevConn")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agent> Agents { get; set; }
        public virtual DbSet<IncludeImportedProduct> IncludeImportedProducts { get; set; }
        public virtual DbSet<IncludeOrderProduct> IncludeOrderProducts { get; set; }
        public virtual DbSet<OrderReceipt> OrderReceipts { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<WarehouseReceipt> WarehouseReceipts { get; set; }
    
        [DbFunction("DevConn", "fnProductsIn")]
        public virtual IQueryable<fnProductsIn_Result> fnProductsIn()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnProductsIn_Result>("[DevConn].[fnProductsIn]()");
        }
    
        [DbFunction("DevConn", "fnProductsOut")]
        public virtual IQueryable<fnProductsOut_Result> fnProductsOut()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnProductsOut_Result>("[DevConn].[fnProductsOut]()");
        }
    
        [DbFunction("DevConn", "fnBestSellingProduct")]
        public virtual IQueryable<fnBestSellingProduct_Result> fnBestSellingProduct()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnBestSellingProduct_Result>("[DevConn].[fnBestSellingProduct]()");
        }
    
        [DbFunction("DevConn", "fnRevenueEachMonth")]
        public virtual IQueryable<fnRevenueEachMonth_Result> fnRevenueEachMonth()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnRevenueEachMonth_Result>("[DevConn].[fnRevenueEachMonth]()");
        }
    }
}
