//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoodsStatistics
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarehouseReceipt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WarehouseReceipt()
        {
            this.IncludeImportedProducts = new HashSet<IncludeImportedProduct>();
        }
    
        public int ReceiptID { get; set; }
        public int TotalWarehouseQuantity { get; set; }
        public int TotalWarehousePrice { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IncludeImportedProduct> IncludeImportedProducts { get; set; }
    }
}
